AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RateMyRickshaw - AI-powered rickshaw detection and analysis application

Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Runtime: java17
    Architectures:
      - x86_64
    Environment:
      Variables:
        QUARKUS_LAMBDA_HANDLER: rickshawAnalysis
        DISABLE_SIGNAL_HANDLERS: true
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  RickshawAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ratemyrickshaw-lambda
      CodeUri: target/function.zip
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Description: Analyzes images for rickshaw detection using AWS Rekognition
      Runtime: java17
      MemorySize: 1024
      Timeout: 120
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - rekognition:DetectLabels
                - rekognition:DetectText
                - rekognition:DetectModerationLabels
              Resource: '*'
      Events:
        AnalyzeImage:
          Type: Api
          Properties:
            Path: /analyze
            Method: POST
            RestApiId: !Ref RickshawApi

  RickshawApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ratemyrickshaw-api
      StageName: prod
      Description: REST API for RateMyRickshaw application
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ratemyrickshaw
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${FrontendBucket.Arn}/*'

Outputs:
  RickshawAnalysisApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub 'https://${RickshawApi}.execute-api.${AWS::Region}.amazonaws.com/prod/analyze'
  
  RickshawAnalysisFunctionArn:
    Description: Rickshaw Analysis Lambda Function ARN
    Value: !GetAtt RickshawAnalysisFunction.Arn
  
  RickshawAnalysisFunctionRole:
    Description: IAM Role created for Rickshaw Analysis function
    Value: !GetAtt RickshawAnalysisFunctionRole.Arn
  
  FrontendBucketName:
    Description: S3 bucket name for frontend hosting
    Value: !Ref FrontendBucket
  
  WebsiteURL:
    Description: URL for website hosted on S3
    Value: !GetAtt FrontendBucket.WebsiteURL
  
  ApiEndpoint:
    Description: API Gateway endpoint URL (base)
    Value: !Sub 'https://${RickshawApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
